<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default metadata</name>
  <uuid>886887b3-3b69-4f52-9e3c-c40ad94f1c01</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set the metadata of decision to the metadata of this decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
