<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ko rule</name>
  <uuid>395dc1ca-ed32-4bc8-a474-dd6f4e7e7417</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Input is false 	
then
	set the result of decision to "KO" ;
    set the metadata of decision to the metadata of this decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
